version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minio1234
    ports:
      - "9000:9000"   # MinIO Web UI
      - "9001:9001"   # MinIO Console
    volumes:
      - minio_data:/data  # Persist MinIO data
    command: server --console-address :9001 /data

volumes:
  minio_data:
    driver: local
